package com.micsig.tbook.tbookscope.middleware.mq;

/**
 * @auother Liwb
 * @description:
 * @data:2024-2-29 10:45
 */
public enum MQEnum {
    NULL("NULL"),
    LOAD_SCOPE_FPGA("LOAD_SCOPE_FPGA"),
    LOAD_SCOPE_UI("LOAD_SCOPE_UI"),
    LOAD_SCOPE_COMPLETE("LOAD_SCOPE_COMPLETE"),

    CH_ACTIVE("CH_ACTIVE"),
    CH_OPEN("CH_OPEN"),
    CH_CLOSE("CH_CLOSE"),

    CH_POSITION("CH_POSITION"),
    CH_INVERT("CH_INVERT"),
    CH_COUPLE("CH_COUPLE"),
    CH_PROBE("CH_PROBE"),
    CH_PROBE_VALUE("CH_PROBE_VALUE"),
    CH_BANDWIDTH("CH_BANDWIDTH"),
    CH_BANDWIDTH_VALUE("CH_BANDWIDTH_VALUE"),
    CH_IMP("CH_IMP"),
    CH_V_SCALE_REF("CH_V_SCALE_REF"),
    CH_LABEL("CH_LABEL"),
    CH_DELAY("CH_DELAY"),
    CH_OFFSET("CH_OFFSET"),
    CH_FINE("CH_FINE"),
    CH_FINE_VALUE("CH_FINE_VALUE"),
    CH_EXTENT("CH_EXTENT"),

    MATH_OPEN("MATH_OPEN"),
    MATH_CLOSE("MATH_CLOSE"),
    MATH_TYPE("MATH_TYPE"),
    MATH_DW_SOURCE1("MATH_DW_SOURCE1"),
    MATH_DW_SOURCE2("MATH_DW_SOURCE2"),
    MATH_DW_OPERATOR("MATH_DW_OPERATOR"),
    MATH_FFT_TYPE("MATH_FFT_TYPE"),
    MATH_FFT_SOURCE("MATH_FFT_SOURCE"),
    MATH_FFT_WINDOW("MATH_FFT_WINDOW"),
    MATH_FFT_PERSIST_TYPE("MATH_FFT_PERSIST_TYPE"),
    MATH_FFT_PERSIST_VALUE("MATH_FFT_PERSIST_VALUE"),
    MATH_AXB_UNIT("MATH_AXB_UNIT"),
    MATH_AXB_SOUCE("MATH_AXB_SOUCE"),
    MATH_AXB_A("MATH_AXB_A"),
    MATH_AXB_B("MATH_AXB_B"),
    MATH_ADV_EXPRESS("MATH_ADV_EXPRESS"),
    MATH_ADV_VALUE1("MATH_ADV_VALUE1"),
    MATH_ADV_VALUE2("MATH_ADV_VALUE2"),
    MATH_ADV_UNIT("MATH_ADV_UNIT"),
    MATH_VERMODE("MATH_VERMODE"),
    MATH_POSITION("MATH_POSITION"),
    MATH_EXTENT("MATH_EXTENT"),

    REF_OPEN("REF_OPEN"),
    REF_CLOSE("REF_CLOSE"),
    REF_EXTENT("REF_EXTENT"),
    REF_POSITION("REF_POSITION"),
    REF_TIMEBASE_X("REF_TIMEBASE_X"),
    REF_TIMEBASE_EXTENT("REF_TIMEBASE_EXTENT"),


    SERIAL_OPEN("SERIAL_OPEN"),
    SERIAL_CLOSE("SERIAL_CLOSE"),
    SERIAL_TYPE("SERIAL_TYPE"),
    SERIAL_UART_SOURCE("SERIAL_UART_SOURCE"),
    SERIAL_UART_IDLE_LEVEL("SERIAL_UART_IDLE_LEVEL"),
    SERIAL_UART_CHECK("SERIAL_UART_CHECK"),
    SERIAL_UART_BIT("SERIAL_UART_BIT"),
    SERIAL_UART_BAUD_RATE("SERIAL_UART_BAUD_RATE"),
    SERIAL_UART_DISPLAY_FORMAT("SERIAL_UART_DISPLAY_FORMAT"),

    SERIAL_LIN_SOURCE("SERIAL_LIN_SOURCE"),
    SERIAL_LIN_IDLE_LEVEL("SERIAL_LIN_IDLE_LEVEL"),
    SERIAL_LIN_BAUD_RATE("SERIAL_LIN_BAUD_RATE"),

    SERIAL_CAN_SOURCE("SERIAL_CAN_SOURCE"),
    SERIAL_CAN_SIGNAL_TYPE("SERIAL_CAN_SIGNAL_TYPE"),
    SERIAL_CAN_BAUD_RATE("SERIAL_CAN_BAUD_RATE"),
    SERIAL_CAN_BAUD_RATE_PERCENT("SERIAL_CAN_BAUD_RATE_PERCENT"),
    SERIAL_CAN_FD_BAUD_RATE("SERIAL_CAN_FD_BAUD_RATE"),
    SERIAL_CAN_FD_BAUD_RATE_PERCENT("SERIAL_CAN_FD_BAUD_RATE_PERCENT"),
    SERIAL_CAN_STANDARD("SERIAL_CAN_STANDARD"),

    SERIAL_SPI_CLOCK_SOURCE("SERIAL_SPI_SOURCE"),
    SERIAL_SPI_CLOCK_LEVEL("SERIAL_SPI_SOURCE_LEVEL"),
    SERIAL_SPI_DATA("SERIAL_SPI_DATA"),
    SERIAL_SPI_DATA_LEVEL("SERIAL_SPI_DATA_LEVEL"),
    SERIAL_SPI_CS_ENABLE("SERIAL_SPI_CS_ENABLE"),
    SERIAL_SPI_CS_SOURCE("SERIAL_SPI_CS_SOURCE"),
    SERIAL_SPI_CS_LEVEL("SERIAL_SPI_CS_LEVEL"),
    SERIAL_SPI_BIT("SERIAL_SPI_BIT"),

    SERIAL_I2C_DATA_SOURCE("SERIAL_I2C_DATA_SOURCE"),
    SERIAL_I2C_CLOCK_SOURCE("SERIAL_I2C_CLOCK_SOURCE"),

    SERIAL_A429_SOURCE("SERIAL_A429_SOURCE"),
    SERIAL_A429_FORMAT("SERIAL_A429_FORMAT"),
    SERIAL_A429_DISPLAY_FORMAT("SERIAL_A429_DISPLAY_FORMAT"),
    SERIAL_A429_BAUD_RATE("SERIAL_A429_BAUD_RATE"),

    SERIAL_M1553B_SOURCE("SERIAL_M1553B_SOURCE"),
    SERIAL_M1553B_DISPLAY_FORMAT("SERIAL_M1553B_DISPLAY_FORMAT"),

    TRIGGER_SRC_CHANGE("TRIGGER_SRC_CHANGE"),
    TRIGGER_TYPE_CHANGE("TRIGGER_TYPE_CHANGE"),
    TRIGGER_LEVEL_CHANGE("TRIGGER_LEVEL_CHANGE"),
    TRIGGER_MOVE_COMPLETE("TRIGGER_MOVE_COMPLETE"),

    THRESHOLD_LEVEL_CHANGE("THRESHOLD_LEVEL_CHANGE"),
    THRESHOLD_SRC_CHANGE("THRESHOLD_SRC_CHANGE"),

    COMPLETE("COMPLETE");

    private String value;

    private  MQEnum(String value){
        this.value=value;
    }
}
