/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_micsig_tbook_tbookscope_scpi_SCPICommandDeal_SCPICommandStruct */

#ifndef _Included_com_micsig_tbook_tbookscope_scpi_SCPICommandDeal_SCPICommandStruct
#define _Included_com_micsig_tbook_tbookscope_scpi_SCPICommandDeal_SCPICommandStruct
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
