/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_micsig_tbook_tbookscope_scpi_SCPICommandDeal */

#ifndef _Included_com_micsig_tbook_tbookscope_scpi_SCPICommandDeal
#define _Included_com_micsig_tbook_tbookscope_scpi_SCPICommandDeal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_micsig_tbook_tbookscope_scpi_SCPICommandDeal
 * Method:    scpiCommand
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_micsig_tbook_tbookscope_scpi_SCPICommandDeal_scpiCommand
  (JNIEnv *, jobject, jstring,jobject);

#ifdef __cplusplus
}
#endif
#endif
